- name: check composer
  stat: path=/usr/local/bin/composer
  register: composer_bin
  tags: composer

- block:
  - name: download composer
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer

  - name: install composer
    shell: cat /tmp/installer | php -- --install-dir=/usr/bin

  - name: rename composer.phar to composer
    shell: mv /usr/bin/composer.phar /usr/bin/composer

  - name: make composer executable
    file:
      path: /usr/bin/composer
      mode: a+x
      state: file

  when: not composer_bin.stat.exists
  tags: composer