- name: install epel-release
  yum: 
    name: epel-release
    state: present

- name: install Remi 
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: install php
  yum: name={{ item }} state=installed
  with_items:
    - php72
    - php72-php
    - php72-php-devel
    - php72-php-mbstring


- name: create php symbolic link
  file:
    src: "/bin/php72"
    dest: "/bin/php"
    state: link